import Head from "next/head";
import Container from "@mui/material/Container";
import Typography from "@mui/material/Typography";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth='md'>
        <Typography variant="h2" sx={{ fontWeight: "bold" }}>
          Construction
        </Typography>        
        <Typography>
          Hi there! Thank you for visiting my website. I'm Philippe, an
          architecture student. My website is currently under maintenance, but
          please check back soon to see my portfolio and learn more about my
          work. <br/>          
          In the meantime, you can find more information about me on my
          social media accounts:
        </Typography>
      </Container>
    </>
  );
}
