
import Navbar from "@/components/Navbar";
import Parkour from "@/components/Parkour";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="relative bg-gray-200 flex top-16 h-[calc(100vh-4rem)] flex-col items-center justify-center p-3 font-body">
        <Parkour />
      </div>
    </>
  );
}
