import { DownloadIco } from "@/components/icons";
import Navbar from "@/components/Navbar";
import menuDrop from "@/recoil/menuDrop";
import { Viewer, Worker } from "@react-pdf-viewer/core";
import Head from "next/head";
import { useSetRecoilState } from "recoil";

export default function Home() {
  const setMenuDrop = useSetRecoilState(menuDrop);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div
        onClick={() => setMenuDrop(false)}
        className="relative top-16 w-full bg-gray-200"
      >
        <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.15.349/build/pdf.worker.js">
          <div className="flex justify-center">
            <div className="w-[calc((100vh-64px)*1.41)]">
              <Viewer fileUrl="https://synologyflupke.synology.me/projects/test/TortaMilanese_boekje.pdf" />
            </div>
          </div>
        </Worker>
      </div>
      <a
        className="fixed bottom-0 flex h-16 w-16 cursor-pointer items-center justify-center border-t border-r border-black bg-white text-sm"
        href="https://synologyflupke.synology.me/projects/test/TortaMilanese_boekje.pdf"
        target="_blank"
      >
        <DownloadIco className="text-2xl" />
      </a>
    </>
  );
}
